#!/usr/bin/env bash
# ================================================================
# EcoHealth — coturn TURN server setup for WebRTC NAT traversal
# ================================================================
# Run this script on the DEDICATED TURN VPS (74.x.x.x).
#
# It installs coturn, generates a strong credential, opens the firewall,
# and writes a ready-to-use config. After it finishes, copy the printed
# ICE_TURN_* values into the backend .env on the main app VPS.
#
# Usage:
#   sudo bash deploy-turn.sh
# ================================================================
set -euo pipefail

# ---- Configurable variables (edit if needed) ----
TURN_REALM="${TURN_REALM:-afridiwins.online}"
TURN_PORT="${TURN_PORT:-3478}"
TURN_USERNAME="${TURN_USERNAME:-sehat}"
# Generate a strong random credential if not provided
TURN_CREDENTIAL="${TURN_CREDENTIAL:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)}"
LISTEN_IP="${LISTEN_IP:-0.0.0.0}"
# Auto-detect the server's public IP
EXTERNAL_IP="${EXTERNAL_IP:-$(curl -s https://api.ipify.org || echo '74.x.x.x')}"

echo "================================================"
echo "  EcoHealth — coturn TURN server setup"
echo "================================================"
echo "Public IP:   $EXTERNAL_IP"
echo "Realm:       $TURN_REALM"
echo "Port:        $TURN_PORT (TCP+UDP)"
echo "Username:    $TURN_USERNAME"
echo "Credential:  $TURN_CREDENTIAL"
echo "================================================"
echo ""

# ---- Install coturn ----
if command -v apt-get &>/dev/null; then
  echo "→ Installing coturn via apt..."
  apt-get update -qq
  apt-get install -y -qq coturn
elif command -v dnf &>/dev/null; then
  echo "→ Installing coturn via dnf..."
  dnf install -y coturn
else
  echo "✗ Unsupported package manager. Please install coturn manually."
  exit 1
fi

# ---- Enable the TURN daemon ----
# On Debian/Ubuntu, coturn is disabled by default via /etc/default/coturn
if [ -f /etc/default/coturn ]; then
  sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
fi

# ---- Write the coturn config ----
CONFIG_FILE="/etc/turnserver.conf"
BACKUP="$CONFIG_FILE.bak.$(date +%s)"
if [ -f "$CONFIG_FILE" ]; then
  cp "$CONFIG_FILE" "$BACKUP"
  echo "→ Backed up existing config to $BACKUP"
fi

cat > "$CONFIG_FILE" <<EOF
# EcoHealth — coturn configuration
# Generated by deploy-turn.sh on $(date)

# Network config
listening-ip=$LISTEN_IP
listening-port=$TURN_PORT
external-ip=$EXTERNAL_IP

# Authentication
realm=$TURN_REALM
user=$TURN_USERNAME:$TURN_CREDENTIAL
lt-cred-mech

# Logging
log-file=/var/log/turnserver.log
simple-log
verbose

# Security
# Block unauthorized relay attempts
no-loopback-peers
no-multicast-peers
# Prevent relay to private IPs (prevents SSRF via TURN)
no-tlsv1
no-tlsv1_1

# Fingerprint for STUN compatibility
fingerprint

# Total relay quota (adjust based on your VPS capacity)
total-quota=100
# Per-user relay quota
user-quota=20
# Max bits-per-second per TURN allocation (256 KB/s — enough for audio/video)
bps-capacity=0

# Disable CLI for security
no-cli
EOF

echo "→ Wrote config to $CONFIG_FILE"

# ---- Open firewall ports ----
# coturn needs: 3478/tcp, 3478/udp, 5349/tcp (TLS), 49152-65535/udp (relay range)
if command -v ufw &>/dev/null; then
  echo "→ Opening firewall ports via ufw..."
  ufw allow $TURN_PORT/tcp
  ufw allow $TURN_PORT/udp
  ufw allow 5349/tcp
  ufw allow 49152:65535/udp
  echo "  ufw rules added."
elif command -v firewall-cmd &>/dev/null; then
  echo "→ Opening firewall ports via firewalld..."
  firewall-cmd --permanent --add-port=$TURN_PORT/tcp
  firewall-cmd --permanent --add-port=$TURN_PORT/udp
  firewall-cmd --permanent --add-port=5349/tcp
  firewall-cmd --permanent --add-port=49152-65535/udp
  firewall-cmd --reload
  echo "  firewalld rules added."
else
  echo "⚠ No firewall manager detected. Manually open these ports:"
  echo "  - $TURN_PORT/tcp"
  echo "  - $TURN_PORT/udp"
  echo "  - 5349/tcp (TLS)"
  echo "  - 49152-65535/udp (relay range)"
fi

# ---- Restart coturn ----
echo "→ Restarting coturn..."
systemctl enable coturn
systemctl restart coturn
sleep 2

if systemctl is-active --quiet coturn; then
  echo "✅ coturn is running"
else
  echo "✗ coturn failed to start. Check: journalctl -u coturn -e"
  exit 1
fi

# ---- Print the env vars to copy to the backend ----
echo ""
echo "================================================"
echo "  ✅ TURN server is ready!"
echo "================================================"
echo ""
echo "Add these to the backend .env on the main app VPS:"
echo ""
echo "  ICE_STUN_URLS=stun:stun.l.google.com:19302,stun:$EXTERNAL_IP:$TURN_PORT"
echo "  ICE_TURN_URLS=turn:$EXTERNAL_IP:$TURN_PORT"
echo "  ICE_TURN_USERNAME=$TURN_USERNAME"
echo "  ICE_TURN_CREDENTIAL=$TURN_CREDENTIAL"
echo ""
echo "Then restart the backend: pm2 restart ecohealth-backend"
echo ""
echo "To test the TURN server, visit:"
echo "  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/"
echo "  Enter: turn:$EXTERNAL_IP:$TURN_PORT  /  $TURN_USERNAME  /  $TURN_CREDENTIAL"
echo "================================================"
